// Generated by dojo-bindgen on Tue, 17 Jun 2025 13:11:31 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::GameSession` model
public class dojo_starter_GameSession : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("start_time")]
        public ulong start_time;

        [ModelField("remaining_time")]
        public uint remaining_time;

        [ModelField("active")]
        public bool active;

        [ModelField("score")]
        public uint score;

        [ModelField("last_update")]
        public ulong last_update;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        