// Generated by dojo-bindgen on Tue, 17 Jun 2025 13:11:31 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::PlayerAction` model
public class dojo_starter_PlayerAction : ModelInstance {
    [ModelField("id")]
        public FieldElement id;

        [ModelField("player")]
        public FieldElement player;

        [ModelField("position")]
        public byte position;

        [ModelField("mole_type")]
        public byte mole_type;

        [ModelField("hit")]
        public bool hit;

        [ModelField("points")]
        public int points;

        [ModelField("client_timestamp")]
        public ulong client_timestamp;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        