// Generated by dojo-bindgen on Tue, 17 Jun 2025 13:11:31 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `dojo_starter::models::PlayerScore` model
public class dojo_starter_PlayerScore : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("score")]
        public uint score;

        [ModelField("high_score")]
        public uint high_score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        